<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWpf>true</UseWpf>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <Version>1.15.6.5</Version>
    <AssemblyVersion>1.15.6.5</AssemblyVersion>
    <FileVersion>1.15.6.5</FileVersion>
    <InformationalVersion>1.15.6.5</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <AssemblyName>AcadBatchPlot</AssemblyName>
    <RootNamespace>ZwcadBatchPlot</RootNamespace>
    <DefineConstants>$(DefineConstants);AUTOCAD</DefineConstants>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin-acad\</OutputPath>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="src\Common\**\*.cs" />
    <Compile Include="src\AutoCAD\**\*.cs" />
    <EmbeddedResource Include="src\AutoCAD\**\*.resx" />

    <ProjectReference Include="src\PianNoCN\PianNoCN.csproj" />
    <None Remove="src\AutoCAD\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="FileTools\**\*.cs" />
    <EmbeddedResource Remove="FileTools\**\*" />
    <None Remove="FileTools\**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="resources\acad\Plotters\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Plotters\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="AutoCAD.NET" Version="20.0.1">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="PDFsharp" Version="1.50.5147" />
    <PackageReference Include="SharpZipLib" Version="1.3.3" />
    <PackageReference Include="System.Resources.Extensions" Version="7.0.0" />
  </ItemGroup>
</Project>
